spring.application.name=my-portafolio-backend
spring.datasource.url=jdbc:postgresql://ep-late-frost-aeufge26-pooler.c-2.us-east-2.aws.neon.tech/portafolio
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XYpJr6UovGm8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.properties.sslmode=require

spring.datasource.hikari.maximun-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always
